# Generated by Django 3.2.7 on 2021-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartofAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialBalance_chart', models.CharField(choices=[('CA', 'Current Asset'), ('NCA', 'Non-Current Asset'), ('CL', 'Current Liability'), ('NCL', 'Non-Current Liability'), ('E', 'Equity'), ('I', 'Income'), ('EX', 'Expenses')], max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
    ]
