# Generated by Django 3.2.7 on 2021-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0005_alter_chartofaccount_trialbalance_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='trialBalance_chart',
            field=models.CharField(max_length=100),
        ),
    ]
