# Generated by Django 3.2.7 on 2021-09-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0006_alter_chartofaccount_trialbalance_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transdate', models.DateField()),
                ('journal', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('check_no_ref', models.CharField(max_length=100)),
                ('journalMemo', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=30)),
                ('trialBalance_chart', models.CharField(max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_module.chartofaccount')),
            ],
        ),
    ]
