# Generated by Django 3.2.7 on 2021-09-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0007_journalentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='trialBalance_chart',
        ),
    ]
