# Generated by Django 3.2.7 on 2021-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0008_auto_20210929_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='account_name',
            field=models.CharField(max_length=500),
        ),
    ]
