# Generated by Django 3.2.7 on 2021-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0009_alter_journalentry_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
