# Generated by Django 3.2.7 on 2021-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0010_auto_20210929_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
