# Generated by Django 3.2.7 on 2021-10-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0013_auto_20210929_2131'),
        ('accounting_module', '0013_auto_20210930_1535'),
    ]

    operations = [
    ]
