# Generated by Django 3.2.7 on 2021-10-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0014_merge_0013_auto_20210929_2131_0013_auto_20210930_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='account_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_module.chartofaccount'),
        ),
    ]
