# Generated by Django 3.2.7 on 2021-10-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0016_alter_journalentry_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='account_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounting_module.chartofaccount'),
        ),
    ]
