# Generated by Django 3.2.7 on 2021-10-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0019_alter_journalentry_account_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={},
        ),
    ]
