# Generated by Django 3.2.7 on 2021-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0020_alter_chartofaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['account_name']},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
