# Generated by Django 3.2.7 on 2021-10-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0021_auto_20211005_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='account_name',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account_name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounting_module.chartofaccount'),
        ),
    ]
