# Generated by Django 3.2.7 on 2021-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0023_alter_journalentry_account_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='account_name_id',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
