# Generated by Django 3.2.7 on 2021-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0025_auto_20211006_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
