# Generated by Django 3.2.7 on 2021-10-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0026_journalentry_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='account_name',
        ),
    ]
