# Generated by Django 3.2.7 on 2021-10-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_module', '0028_rename_account_name_id_journalentry_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
